apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: saas-proxy
  namespace: teamcrm
  labels:
    team: teamcrm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
spec:
  image: '{{ image }}'
  port: 8080
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  preStopHook:
    exec:
      command: [ "/bin/bash", "/pre-stop.sh" ]
  terminationGracePeriodSeconds: 60
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 512Mi
  ingresses:
    - "https://saas-proxy.ekstern.dev.nav.no"
    - "https://saas-proxy.intern.dev.nav.no"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - azp_name
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: dev-external
    outbound:
      rules:
        - application: veilarbapi
          namespace: pto
        - application: sf-brukernotifikasjon
          namespace: teamnks
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: sokos-kontoregister-person
          namespace: okonomi
        - application: nom-api
          namespace: nom
        - application: sf-pdfgen
          namespace: teamcrm
        - application: notifikasjon-produsent-api
          namespace: fager
        - application: sf-arkiv-proxy
          namespace: teamcrm
        - application: sf-websak-proxy
          namespace: teamcrm
        - application: pam-cv-api-gcp
          namespace: teampam
        - application: paw-arbeidssoekerregisteret-api-oppslag
          namespace: paw
  env:
    - name: WHITELIST_FILE
      value: '/whitelist/dev.json'
    - name: INGRESS_FILE
      value: '/ingresses/dev.json'
