apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: saas-proxy
  namespace: teamcrm
  labels:
    team: teamcrm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  preStopHook:
    exec:
      command: ["/bin/bash", "/pre-stop.sh"]
  terminationGracePeriodSeconds: 60
  valkey:
    - instance: saasproxy # Determines env variable names
      access: readwrite
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  ingresses:
    - "https://saas-proxy.ekstern.dev.nav.no"
    - "https://saas-proxy.intern.dev.nav.no"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - azp_name
          - NAVident
    sidecar:
      enabled: false # Currently cannot use - causes 404 when app tries calling dev-fss-pub.nais.io ingresses
  accessPolicy:
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: dev-external
        - application: itestapp
          namespace: teamcrm
        - application: simtest
          namespace: teamcrm
    outbound:
      rules:
        - application: veilarbapi
          namespace: pto
        - application: sf-brukernotifikasjon
          namespace: teamnks
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: sokos-kontoregister-person
          namespace: okonomi
        - application: sokos-skattekort
          namespace: okonomi
        - application: nom-api
          namespace: nom
        - application: sf-pdfgen
          namespace: teamcrm
        - application: notifikasjon-produsent-api
          namespace: fager
        - application: pam-cv-api-gcp
          namespace: teampam
        - application: paw-arbeidssoekerregisteret-api-oppslag
          namespace: paw
        - application: paw-arbeidssoekerregisteret-api-oppslag-v2
          namespace: paw
        - application: tiltakspenger-datadeling
          namespace: tpts
        - application: norg2
          namespace: org
        - application: repr-api
          namespace: repr
        - application: hm-saksbehandling
          namespace: teamdigihot
        - application: api-intern
          namespace: aap
        - application: dp-datadeling
          namespace: teamdagpenger
        - application: aareg-tilgangskontroll-q2
          namespace: arbeidsforhold
        - application: pensjon-pid-encryption
          namespace: pensjon-person
      external:
        - host: "sf-arkiv-dokumentasjon.dev-fss-pub.nais.io"
        - host: "sf-websak.dev-fss-pub.nais.io"
        - host: "sf-brukervarsel-proxy.dev-fss-pub.nais.io"
        - host: "saf-q2.dev-fss-pub.nais.io"
        - host: "oppgave-q1.dev-fss-pub.nais.io"
        - host: "dokarkiv-q2.dev-fss-pub.nais.io"
        - host: "regoppslag.dev-fss-pub.nais.io"
        - host: "arena-api-q2.dev-fss-pub.nais.io"
        - host: "sokos-utbetaldata.dev-fss-pub.nais.io"
        - host: "sosialhjelp-modia-api.dev-fss-pub.nais.io"
        - host: "axsys.dev-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "sokos-kontoregister-q2.dev-fss-pub.nais.io"
        - host: "dokument1-q.adeo.no"
        - host: "oebs-digihot-api-q1.dev-fss-pub.nais.io"
        - host: "oebs-digihot-api-q2.dev-fss-pub.nais.io"
        - host: "oebs-digihot-api-t1.dev-fss-pub.nais.io"
        - host: "pensjon-pen-q2.dev-fss-pub.nais.io"
  envFrom:
    - secret: salesforce-entra
  env:
    - name: WHITELIST_FILE
      value: "/whitelist/dev.json"
    - name: INGRESS_FILE
      value: "/ingresses/dev.json"
