apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: saas-proxy
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 3
    max: 5
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - "https://saas-proxy.nav.no"
    - "https://saas-proxy.intern.nav.no"
  azure:
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
    outbound:
      rules:
        - application: veilarbapi
          namespace: pto
        - application: sf-brukernotifikasjon
          namespace: teamnks
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: sokos-kontoregister-person
          namespace: okonomi
  env:
    - name: WHITELIST_FILE
      value: '/whitelist/prod.json'
