apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: saas-proxy
  namespace: teamcrm
  labels:
    team: teamcrm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
spec:
  image: '{{ image }}'
  port: 8080
  replicas:
    min: 12
    max: 12
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  preStopHook:
    exec:
      command: [ "/bin/bash", "/pre-stop.sh" ]
  terminationGracePeriodSeconds: 60
  valkey:
    - instance: saasproxy # Determines env variable names
      access: readwrite
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  ingresses:
    - "https://saas-proxy.nav.no"
    - "https://saas-proxy.intern.nav.no"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - azp_name
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
    outbound:
      rules:
        - application: veilarbapi
          namespace: pto
        - application: sf-brukernotifikasjon
          namespace: teamnks
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: sokos-kontoregister-person
          namespace: okonomi
        - application: nom-api
          namespace: nom
        - application: sf-arkiv
          namespace: teamcrm
          cluster: prod-fss
        - application: sf-pdfgen
          namespace: teamcrm
        - application: notifikasjon-produsent-api
          namespace: fager
        - application: pam-cv-api-gcp
          namespace: teampam
        - application: paw-arbeidssoekerregisteret-api-oppslag
          namespace: paw
        - application: tiltakspenger-datadeling
          namespace: tpts
        - application: norg2
          namespace: org
        - application: repr-api
          namespace: repr
        - application: hm-saksbehandling
          namespace: teamdigihot
        - application: aareg-tilgangskontroll
          namespace: arbeidsforhold
      external:
        - host: "sf-arkiv-dokumentasjon.prod-fss-pub.nais.io"
        - host: "sf-websak.prod-fss-pub.nais.io"
        - host: "sf-brukervarsel-proxy.prod-fss-pub.nais.io"
        - host: "saf.prod-fss-pub.nais.io"
        - host: "oppgave.prod-fss-pub.nais.io"
        - host: "dokarkiv.prod-fss-pub.nais.io"
        - host: "regoppslag.prod-fss-pub.nais.io"
        - host: "arena-api.prod-fss-pub.nais.io"
        - host: "sokos-skattekort-person.prod-fss-pub.nais.io"
        - host: "sokos-utbetaldata.prod-fss-pub.nais.io"
        - host: "sosialhjelp-modia-api.prod-fss-pub.nais.io"
        - host: "axsys.prod-fss-pub.nais.io"
        - host: "sokos-kontoregister.prod-fss-pub.nais.io"
        - host: "pdl-api.prod-fss-pub.nais.io"
        - host: "dokument1.adeo.no"
        - host: "oebs-digihot-api.prod-fss-pub.nais.io"
        - host: "pensjon-pen.prod-fss-pub.nais.io"
  env:
    - name: WHITELIST_FILE
      value: '/whitelist/prod.json'
    - name: INGRESS_FILE
      value: '/ingresses/prod.json'
